### ISSUE TITLE
Have a Error

### ISSUE THREAD

**Issue by huikangzhijia** [horvey/Library-Manager#1]
Parse error: syntax error, unexpected 'return' (T_RETURN), expecting identifier (T_STRING) in D:\lunTan34\htdocs\Library\Admin\Controller\BorrowController.class.php on line 95

**Comment by huikangzhijia** [comment]
修改方法：return是关键字，用关键字定义函数名是这个错误的主要原因，所以请把return这个函数名进行替换替换成别的函数名
 public function return1(){
        $this->accessJson();

        $bookId = $_POST['bookId'];
        $userId = $_POST['userId'];

        $borrowModel = new BorrowModel;
        if($borrowModel->canReturn($bookId,$userId)){
            if($borrowModel->delete("book_id={$bookId} AND user_id={$userId}")){
                $this->sendJsonMessage("还书成功",0);
            }else{
                $this->sendJsonMessage("还书失败",1);
            }
        }else{
            $this->sendJsonMessage("信息错误或该用户未借此书",1);
        }
    }

**Comment by horvey** [comment]
已修复
